# Fazit und Ausblick
Hier schreiben wir Fazit von dem Experiment 

Wenn wir nun noch einmal einen Blick darauf werfen, was wir im Verlauf dieses Labor ereicht haben, können wir behaupten, dass dieses ein Erfolg war.
Wir konnten das Wissen, welches wir uns in vorherigen Semestern angeeignet haben, sinnvoll nutzen, um unsere eigenes Platinen Design zu erstellen und haben somit unser Ziel erreicht.
Natürlich lief aber nicht immer alles nach Plan. Zu begin hat unsere Steckbrett-Schaltung nicht funktioniert, wodurch wir Zeit für die Fehlersuche aufbringen mussten. Am Ende stellte sich herraus das die Schaltung nicht das Problem war, sondern das Steckbrett.
Es sind aber auch Fehler aufgetreten, dessen Ursache von uns aus ging. Wir haben einen $10k\omega$  Widerstand anstatt einse $1k\omega$  Widerstands benutzt, weshalb wir eine Dämpfung in unserer Schaltung vorliegen hatten.
Auch diesen Fehler konnten wir ausfindig machen und beheben. Diese Probleme haben uns gezeigt, dass nicht immer alles nach Plan laufen kann und auch noch so kleine Fehler einen aufhalten können.
Doch im Endeffekt sind diese Fehler etwas gutes, da sie uns zeigen, dass man immer alles doppelt und dreifach überprüfen muss und das Unaufmerksamkeiten Folgen mit sich führen.
Doch wir wollen nicht nur auf das negative einen Blick werfen. Das von uns erstellte Platinen Design funktioniert genauso wie es soll, die einzelnen Filter geben den gewünschten Verlauf aus und haben keine Dämpfung.
Ebenso funktioniert der von uns erstellte Butterworth Filter auf der Platine so wie es zu erwarten war. Die Fehler die wir zu beginn des Labores gemacht haben, zeigten uns, vorauf wir im weitern Verlauf achten mussten.
Das wissen was wir uns in diesem Labor angeeignet haben, wird uns auch in Zukunft helfen, wenn wir auf ähnliche Probleme stoßen.


Was ist rausgekommen?
Was lief gut, wo gab’s Schwierigkeiten?
Was könnte man als Nächstes machen?
